# Generated by Django 2.1.2 on 2019-09-06 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tnstarget',
            options={'get_latest_by': ('-name',), 'ordering': ('-id',)},
        ),
    ]
